version: '3.7'
services:
  app:
    build: .
    network_mode: host
    ports:
      - "127.0.0.1:8081:8081"
    env_file: .env
    environment:
      FLASK_ENV: 'production'
    volumes:
      - .:/rotk.net

#networks:
#  vswitch0:
#    driver: bridge
