version: '3.7'
services:
  app:
    build: .
    networks:
      - vswitch0
    env_file: .env
    environment:
      FLASK_ENV: 'development'
    ports:
      - "80:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 10s
      retries: 5
      start_period: 1s
    volumes:
      - .:/rotk.net
  db:
    image: "mysql:8.4"
    env_file: .env
    networks:
      - vswitch0
    ports:
      - "32000:3306"
    restart: unless-stopped
    volumes:
      - ./db-data:/var/lib/mysql
      - ./db-confs:/etc/mysql/conf.d
      - ./db-init:/docker-entrypoint-initdb.d:ro

networks:
  vswitch0:
    driver: bridge
